# Generated by Django 5.0.6 on 2024-07-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='checked_out',
        ),
    ]
